# Generated by Django 6.0.4 on 2026-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
